### ISSUE TITLE
How to use it, if there is a video, how to infer, like aot-benchmark demo？

### ISSUE THREAD

**Issue by zhanghongyong123456** [yamy-cheng/DMAOT-VOTS2023#2]
![image](https://github.com/yamy-cheng/DMAOT-VOTS2023/assets/48466610/cc54b0dc-502d-4058-8e15-22e82436aa48)

https://github.com/yoxu515/aot-benchmark?tab=readme-ov-file#demo---panoptic-propagation

**Comment by yamy-cheng** [comment]
Yes, you can modify the `EngineConfig` parameter in [tools/demo.py](https://github.com/yamy-cheng/DMAOT-VOTS2023/blob/master/dmaot/tools/demo.py) to utilize the `dmaot engine` for video inference.

**Comment by zhanghongyong123456** [comment]
> Yes, you can modify the `EngineConfig` parameter in [tools/demo.py](https://github.com/yamy-cheng/DMAOT-VOTS2023/blob/master/dmaot/tools/demo.py) to utilize the `dmaot engine` for video inference.

thanks when，i run  vot initialize vots2023 --workspace Outputs    have   this  error ：Traceback (most recent call last):
  File "H:\Anaconda3\envs\dmaot\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\Anaconda3\envs\dmaot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "H:\Anaconda3\envs\dmaot\Scripts\vot.exe\__main__.py", line 4, in <module>
  File "H:\Anaconda3\envs\dmaot\lib\site-packages\vot\utilities\cli.py", line 9, in <module>
    from ..tracker import Registry, TrackerException
  File "H:\Anaconda3\envs\dmaot\lib\site-packages\vot\tracker\__init__.py", line 14, in <module>
    from vot.dataset import Frame
  File "H:\Anaconda3\envs\dmaot\lib\site-packages\vot\dataset\__init__.py", line 11, in <module>
    from trax import Region
  File "H:\Anaconda3\envs\dmaot\lib\site-packages\trax\__init__.py", line 7, in <module>
    from ._ctypes import \
  File "H:\Anaconda3\envs\dmaot\lib\site-packages\trax\_ctypes.py", line 503, in <module>
    _libs["libtrax"] = load_library("libtrax")
  File "H:\Anaconda3\envs\dmaot\lib\site-packages\trax\_ctypes.py", line 191, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load libtrax.
The only difference in my environment is the different versions of torch（default： torch==1.10.1+cu102  My： torch==1.13.0+cu117（my cuda：11.7））

**Comment by yamy-cheng** [comment]
It seems that there is an issue with the `vot-toolkit`. Would you like to reinstall it?

**Comment by zhanghongyong123456** [comment]
> It seems that there is an issue with the `vot-toolkit`. Would you like to reinstall it?

OK，thanks，Which is easier to succeed with pip installation or git clone source code installation

**Comment by zhanghongyong123456** [comment]
> Yes, you can modify the `EngineConfig` parameter in [tools/demo.py](https://github.com/yamy-cheng/DMAOT-VOTS2023/blob/master/dmaot/tools/demo.py) to utilize the `dmaot engine` for video inference.

I can't find the place you said to set the dmaot engine, can you guide me to modify it，
![image](https://github.com/yamy-cheng/DMAOT-VOTS2023/assets/48466610/fbba7914-952a-46cd-a26a-8a3d6a8a961d)
![image](https://github.com/yamy-cheng/DMAOT-VOTS2023/assets/48466610/75a11a5d-41f9-4369-b20e-1f21f4e6087d)

**Comment by zhanghongyong123456** [comment]
> Yes, you can modify the `EngineConfig` parameter in [tools/demo.py](https://github.com/yamy-cheng/DMAOT-VOTS2023/blob/master/dmaot/tools/demo.py) to utilize the `dmaot engine` for video inference.
I'm not sure which one is right，
![image](https://github.com/yamy-cheng/DMAOT-VOTS2023/assets/48466610/74621621-d0c1-4e79-9f8d-3824e65e0f85)

**Comment by yamy-cheng** [comment]
> > Yes, you can modify the `EngineConfig` parameter in [tools/demo.py](https://github.com/yamy-cheng/DMAOT-VOTS2023/blob/master/dmaot/tools/demo.py) to utilize the `dmaot engine` for video inference.
> > I'm not sure which one is right，
> > ![image](https://private-user-images.githubusercontent.com/48466610/292143488-74621621-d0c1-4e79-9f8d-3824e65e0f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDgwMTgsIm5iZiI6MTcwMzE0NzcxOCwicGF0aCI6Ii80ODQ2NjYxMC8yOTIxNDM0ODgtNzQ2MjE2MjEtZDBjMS00ZTc5LTlmOGQtMzgyNGU2NWUwZjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA4MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZmZiNDQ1YTJlY2Q4NTMwYTNiMDZmZjJiYjM3NTFhZjZhZWM5OWJiYjUxYTA4MzI3MGU0OWYzNjQ0YmFiNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cPPV8IUeTjW8vBRJHeaj-4l3f3XPHL3mpGJRSHC9Azc)

You can pull the latest version of the code and use the following command to perform video inference using r50_dm_deaot. `python tools/demo.py --model r50_dm_deaotl --ckpt_path path for r50-DeAOT --max_long 10`.

**Comment by zhanghongyong123456** [comment]
> > > Yes, you can modify the `EngineConfig` parameter in [tools/demo.py](https://github.com/yamy-cheng/DMAOT-VOTS2023/blob/master/dmaot/tools/demo.py) to utilize the `dmaot engine` for video inference.
> > > I'm not sure which one is right，
> > > ![image](https://private-user-images.githubusercontent.com/48466610/292143488-74621621-d0c1-4e79-9f8d-3824e65e0f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDgwMTgsIm5iZiI6MTcwMzE0NzcxOCwicGF0aCI6Ii80ODQ2NjYxMC8yOTIxNDM0ODgtNzQ2MjE2MjEtZDBjMS00ZTc5LTlmOGQtMzgyNGU2NWUwZjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA4MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZmZiNDQ1YTJlY2Q4NTMwYTNiMDZmZjJiYjM3NTFhZjZhZWM5OWJiYjUxYTA4MzI3MGU0OWYzNjQ0YmFiNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cPPV8IUeTjW8vBRJHeaj-4l3f3XPHL3mpGJRSHC9Azc)
> 
> You can pull the latest version of the code and use the following command to perform video inference using r50_dm_deaot. `python tools/demo.py --model r50_dm_deaotl --ckpt_path path for r50-DeAOT --max_long 10`.

thanks,It's OK
